name: cesam
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  logger: ^2.4.0
  dio: ^5.7.0
  equatable: ^2.0.5
  http: ^1.2.2
  shared_preferences: ^2.3.0
  provider: ^6.1.2
  timezone: ^0.10.1
  syncfusion_flutter_pdfviewer: ^27.2.5
  permission_handler: ^11.0.1
  file_picker: ^10.2.1
  image_picker: ^1.1.0
  open_file: ^3.3.2
  badges: ^3.1.1
  google_fonts: ^6.1.0
  carousel_slider: ^5.1.1
  cupertino_icons: ^1.0.8
  path: ^1.9.0
  path_provider: ^2.1.1
  url_launcher: ^6.3.1
  firebase_messaging: ^14.6.6
  video_player: ^2.6.1
  youtube_player_flutter: ^9.1.2
  webview_flutter: ^4.2.1
  flutter_inappwebview: ^6.1.5
  excel: ^4.0.3
  syncfusion_flutter_xlsio: ^27.2.5
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo_cesam.png
    - assets/banner1.jpeg
    - assets/banner2.jpeg
    - assets/banner3.jpeg
    - assets/fonts/Pacifico-Regular.ttf
    - assets/pdfs/politique.pdf 

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf

# 👇 Ajoute la config launcher icons ICI (pas dans flutter:)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/app_icon.png"
